openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for user operations

paths:
  /users:
    get:
      summary: Get all users
      tags: 
        - Users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hi from GET users"
        "401":
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
                example: "Access denied"
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
                example: "Invalid token"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error message"

  /users/login:
    post:
      summary: User login
      tags: 
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "user1"
                password:
                  type: string
                  example: "password123"
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "jwt-token"
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
                example: "User not found"

  /users/register:
    post:
      summary: User registration
      tags: 
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "newuser"
                password:
                  type: string
                  example: "newpassword123"
      responses:
        "201":
          description: User registered successfully
          content:
            text/plain:
              schema:
                type: string
                example: "User registered successfully"
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
                example: "Username and password are required"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

